import { BookOpen, Calculator, Clock, Languages, MapPin, Users } from "lucide-react"

import { LeadForm } from "@/components/forms/lead-form"
import { PublicFooter, PublicHeader } from "@/components/shared/public-shell"
import { Card, CardContent } from "@/components/ui/card"

const supportAreas = ["Apoyo con deberes", "Lectura y escritura", "Confianza en matemáticas", "Apoyo con inglés"]
const services = [
  { title: "Deberes, sin estrés", description: "Un espacio centrado para terminar los deberes, con un tutor cerca para orientar, animar y ayudar a mantener el ritmo.", icon: BookOpen },
  { title: "Lectura y escritura", description: "Apoyo práctico con lectura, escritura, comprensión, vocabulario y ortografía en inglés.", icon: Languages },
  { title: "Confianza en matemáticas", description: "Tiempo y apoyo para practicar matemáticas, resolver dudas y ganar confianza paso a paso.", icon: Calculator },
  { title: "Una rutina fiable", description: "Una hora estructurada después del colegio que ayuda a los niños a asentarse, concentrarse y llegar a casa con menos por hacer.", icon: Clock },
  { title: "Grupos reducidos", description: "Grupos pequeños y cercanos, para que cada niño se sienta conocido y reciba el ánimo adecuado.", icon: Users },
  { title: "Alineado con el currículo británico", description: "Pensado para familias de colegios británicos e internacionales, en un entorno de aprendizaje en inglés.", icon: MapPin },
]

export const metadata = { title: "Apoyo académico en inglés en Madrid", description: "Apoyo académico extraescolar en grupos reducidos para niños de 4 a 12 años en Arturo Soria, Madrid." }

export default function SpanishHomePage() {
  return <main className="min-h-screen"><PublicHeader locale="es" switchHref="/" />
    <section className="brand-shell flex flex-col gap-16 py-10 md:py-16">
      <section className="brand-hero grid gap-10 p-6 md:p-10 lg:grid-cols-[1fr_380px] lg:items-center"><div className="space-y-7"><div className="brand-pill">Abierto en Arturo Soria · Edades 4–12</div><div className="space-y-5"><h1 className="max-w-3xl text-4xl font-bold tracking-tight md:text-6xl">Apoyo para el currículo británico en Madrid.</h1><p className="max-w-2xl text-lg brand-muted md:text-xl">Apoyo extraescolar tranquilo en grupos reducidos para familias internacionales — ayudamos a los niños a terminar deberes y ganar confianza en inglés, lectura, escritura y matemáticas.</p><p className="max-w-2xl brand-muted">Acogemos a niños de 4 a 12 años en Calle Asura 40. Solicita una plaza y confirmaremos el mejor grupo y horario disponible para tu hijo/a.</p></div><div className="flex flex-col gap-3 sm:flex-row"><a href="#apply" className="brand-button">Solicita una plaza</a><a href="#sesiones" className="brand-button-secondary">Ver sesiones y precios</a></div><div className="grid gap-3 sm:grid-cols-2">{supportAreas.map((item) => <Card key={item} className="brand-card"><CardContent className="p-4 text-sm font-medium">{item}</CardContent></Card>)}</div></div>
      <Card className="brand-card border-[color:var(--brand-gold)] bg-[rgba(255,250,240,0.92)]"><CardContent className="space-y-6 p-7"><div><p className="brand-kicker">Precio sencillo</p><p className="mt-2 text-5xl font-bold tracking-tight">25 €</p><p className="text-lg font-semibold">por niño/a y sesión</p></div><div className="space-y-3 border-y py-5 text-sm brand-muted"><p><strong className="text-foreground">Lunes, martes, jueves y viernes</strong></p><p><strong className="text-foreground">17:00–17:50 o 18:00–18:50</strong></p><p>Calle Asura 40, 28043 Madrid<br />Primera planta, Aula 3</p></div><p className="text-sm brand-muted">Las plazas se asignan según la edad y disponibilidad. No se realiza ningún pago al solicitar plaza.</p><a href="#apply" className="brand-button w-full">Solicita una plaza</a></CardContent></Card></section>
      <section className="grid gap-6 md:grid-cols-[0.8fr_1.2fr]"><Card className="brand-card"><CardContent className="space-y-3 p-6"><p className="brand-kicker">Para las familias</p><h2 className="text-2xl font-semibold">Menos estrés con los deberes. Más calma en casa.</h2></CardContent></Card><Card className="brand-card"><CardContent className="space-y-4 p-6 brand-muted"><p>Después de un largo día escolar, los deberes pueden acabar siendo apresurados o estresantes. The Afternoon Academy ofrece a los niños un lugar tranquilo para asentarse, concentrarse y avanzar antes de llegar a casa.</p><p>Es apoyo académico estructurado: no es cuidado infantil ni sustituye una enseñanza especializada. En esta fase, nuestro enfoque es sencillo: buenas rutinas, deberes terminados y más confianza.</p></CardContent></Card></section>
      <section id="sesiones" className="scroll-mt-10 space-y-6"><div className="max-w-3xl space-y-3"><p className="brand-kicker">Qué hacemos</p><h2 className="text-3xl font-bold tracking-tight">Una hora centrada después del colegio</h2><p className="brand-muted">Cada niño es distinto, pero todas las sesiones son tranquilas, motivadoras y con un objetivo claro.</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map((service) => { const Icon = service.icon; return <Card key={service.title} className="brand-card"><CardContent className="space-y-4 p-6"><div className="flex h-12 w-12 items-center justify-center rounded-2xl border bg-white/75"><Icon className="h-5 w-5" /></div><div className="space-y-2"><h3 className="font-semibold">{service.title}</h3><p className="text-sm brand-muted">{service.description}</p></div></CardContent></Card> })}</div></section>
      <section className="grid gap-6 lg:grid-cols-2"><Card className="brand-card"><CardContent className="space-y-5 p-6"><p className="brand-kicker">Sesiones</p><h2 className="text-3xl font-bold tracking-tight">Elige el horario que mejor encaje</h2><div className="grid gap-3 sm:grid-cols-2">{["17:00–17:50", "18:00–18:50"].map((time) => <div key={time} className="rounded-2xl border bg-white/60 p-4"><p className="text-xl font-semibold">{time}</p><p className="mt-1 text-sm brand-muted">Lunes, martes, jueves y viernes</p></div>)}</div></CardContent></Card><Card className="brand-card"><CardContent className="space-y-5 p-6"><p className="brand-kicker">Ubicación</p><h2 className="text-3xl font-bold tracking-tight">Calle Asura 40</h2><p className="brand-muted">Primera planta, Aula 3 · 28043 Madrid · Arturo Soria</p><p className="brand-muted">Un aula luminosa y dedicada, con espacio para que los grupos reducidos trabajen con calma después del colegio.</p><a href="/es/ubicacion" className="brand-button-secondary">Ver la ubicación</a></CardContent></Card></section>
      <section id="apply" className="scroll-mt-10"><Card className="brand-form-panel"><CardContent className="grid gap-8 p-6 md:p-8 lg:grid-cols-[360px_1fr]"><div className="space-y-4"><div className="brand-pill-warm">Solicita ahora</div><div className="space-y-3"><h2 className="text-3xl font-bold tracking-tight">Solicita una plaza</h2><p className="brand-muted">Cuéntanos un poco sobre tu hijo/a y qué sesiones podrían encajar con tu familia.</p><p className="text-sm brand-muted">Te contactaremos para confirmar disponibilidad y próximos pasos. Solicitar plaza no implica una reserva ni pago.</p></div></div><LeadForm language="es" /></CardContent></Card></section>
    </section><PublicFooter locale="es" switchHref="/" /></main>
}
