import { createAcademySession, createTutorRoomBooking, saveLeadSessionOffer } from "@/actions/learners"
import { LeadOfferActions } from "@/components/admin/lead-offer-actions"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { supabaseAdmin } from "@/lib/supabase/admin"

const days = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
const dayLabel = (day: string) => day[0].toUpperCase() + day.slice(1)

export default async function SessionsPage() {
  const [sessionsR, placementsR, offersR, learnersR, leadsR, bookingsR] = await Promise.all([
    supabaseAdmin.from("academy_sessions").select("*").eq("room_name", "TAA1").order("weekday").order("starts_at"),
    supabaseAdmin.from("session_placements").select("session_id, learner_id, status"),
    supabaseAdmin.from("session_offers").select("id, session_id, parent_lead_id, learner_first_name, learner_year_group, status, fit_note"),
    supabaseAdmin.from("learners").select("id, first_name, year_group").neq("status", "left").order("first_name"),
    supabaseAdmin.from("parent_leads").select("id, parent_name, status").not("status", "in", '("converted","closed")').order("created_at", { ascending: false }),
    supabaseAdmin.from("tutor_room_bookings").select("id, learner_id, parent_lead_id, teacher_name, starts_at, ends_at, note").order("starts_at").limit(20),
  ])
  const sessions = sessionsR.data || []; const placements = placementsR.data || []; const offers = offersR.data || []
  const learners = learnersR.data || []; const leads = leadsR.data || []; const bookings = bookingsR.data || []
  const learnerName = new Map(learners.map((learner) => [learner.id, learner.first_name]))
  const leadName = new Map(leads.map((lead) => [lead.id, lead.parent_name]))

  return <div className="space-y-8">
    <div><p className="text-sm text-muted-foreground">Launch operations</p><h2 className="text-3xl font-bold tracking-tight">TAA timetable and rooms</h2><p className="mt-2 max-w-3xl text-muted-foreground">TAA1 is your flexible weekly homework-support room. The Tutor Room is booked individually by date and time. A place is only enrolled after the parent accepts a specific offer.</p></div>
    <Card><CardHeader><CardTitle>TAA1 — weekly seat plan</CardTitle></CardHeader><CardContent className="grid gap-4 lg:grid-cols-7">{days.map((day) => <div key={day} className="min-h-40 rounded-lg border p-3"><p className="mb-3 font-medium">{dayLabel(day)}</p>{sessions.filter((session) => session.weekday === day).map((session) => { const filled = placements.filter((p) => p.session_id === session.id && p.status === "confirmed").map((p) => learnerName.get(p.learner_id) || "Learner"); return <div key={session.id} className="mb-3 rounded border bg-muted/30 p-2 text-xs"><p className="font-medium">{session.starts_at.slice(0,5)} · {session.teacher_name || "Teacher to assign"}</p><p className="text-muted-foreground">6-seat TAA1 table</p><div className="mt-2 grid grid-cols-2 gap-1">{Array.from({length: 6}, (_, index) => <span key={index} className="rounded bg-background p-1">{filled[index] || "Empty seat"}</span>)}</div></div> })}{!sessions.some((session) => session.weekday === day) && <p className="text-xs text-muted-foreground">No recurring slot yet.</p>}</div>)}</CardContent></Card>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card><CardHeader><CardTitle>Add a TAA1 recurring slot</CardTitle></CardHeader><CardContent><form action={createAcademySession} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="roomName" value="TAA1"/><input type="hidden" name="capacity" value="6"/><input type="hidden" name="status" value="open"/><input type="hidden" name="focus" value="General homework support"/><Input name="name" required placeholder="TAA1 homework support"/><select name="weekday" className="h-10 rounded-md border bg-background px-3">{days.map((day) => <option key={day} value={day}>{dayLabel(day)}</option>)}</select><Input name="startsAt" type="time" required/><Input name="durationMinutes" type="number" min="15" max="360" defaultValue="50" required/><Input name="teacherName" placeholder="Teacher (e.g. Jessica)"/><Input name="ageRange" placeholder="Optional year range"/><Button className="w-fit">Add TAA1 slot</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle>Tutor Room — book one-to-one</CardTitle></CardHeader><CardContent><form action={createTutorRoomBooking} className="grid gap-3 sm:grid-cols-2"><select name="learnerId" className="h-10 rounded-md border bg-background px-3"><option value="">Existing learner (optional)</option>{learners.map((learner) => <option key={learner.id} value={learner.id}>{learner.first_name}</option>)}</select><select name="parentLeadId" className="h-10 rounded-md border bg-background px-3"><option value="">Or parent lead (optional)</option>{leads.map((lead) => <option key={lead.id} value={lead.id}>{lead.parent_name}</option>)}</select><Input name="teacherName" required placeholder="Teacher"/><Input name="startsAt" type="datetime-local" required/><Input name="endsAt" type="datetime-local" required/><Textarea name="note" className="sm:col-span-2" placeholder="Optional booking note"/><Button className="w-fit">Book Tutor Room</Button></form><div className="mt-4 space-y-1 text-sm">{bookings.length ? bookings.map((booking) => <p key={booking.id}>{new Intl.DateTimeFormat("en-GB", { dateStyle:"medium", timeStyle:"short" }).format(new Date(booking.starts_at))}–{new Date(booking.ends_at).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})} · {learnerName.get(booking.learner_id || "") || leadName.get(booking.parent_lead_id || "") || "Booked"} · {booking.teacher_name}</p>) : <p className="text-muted-foreground">No Tutor Room bookings yet.</p>}</div></CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle>Offer a TAA1 place</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">Create the offer from the parent lead. On accepted confirmation, TAA creates the learner record automatically and fills a seat.</p><form action={saveLeadSessionOffer} className="grid gap-3 md:grid-cols-3"><select name="sessionId" className="h-10 rounded-md border bg-background px-3" required><option value="">TAA1 slot</option>{sessions.map((session) => <option key={session.id} value={session.id}>{dayLabel(session.weekday)} {session.starts_at.slice(0,5)} · {session.teacher_name || "TAA1"}</option>)}</select><select name="parentLeadId" className="h-10 rounded-md border bg-background px-3" required><option value="">Parent lead</option>{leads.map((lead) => <option key={lead.id} value={lead.id}>{lead.parent_name}</option>)}</select><Input name="learnerFirstName" required placeholder="Child first name"/><Input name="learnerYearGroup" placeholder="Year group (optional)"/><Textarea name="fitNote" className="md:col-span-2" placeholder="Optional practical note"/><Button className="w-fit">Save proposed offer</Button></form>{offers.length > 0 && <div className="mt-5 space-y-2">{offers.map((offer) => <div key={offer.id} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3"><p className="text-sm"><strong>{offer.learner_first_name}</strong> · {leadName.get(offer.parent_lead_id)} · <span className="capitalize">{offer.status}</span></p><LeadOfferActions offerId={offer.id} status={offer.status}/></div>)}</div>}</CardContent></Card>
  </div>
}
