import { RenewalWorkflowTable, type RenewalWorkflowRow } from "@/components/admin/renewal-workflow-table"
import { supabaseAdmin } from "@/lib/supabase/admin"

const iso = (date: Date) => date.toISOString().slice(0, 10)

export default async function RenewalsPage() {
  const today = new Date(); const horizon = new Date(today); horizon.setDate(horizon.getDate() + 21); const lookback = new Date(today); lookback.setDate(lookback.getDate() - 90)
  const [{ data: entitlements }, { data: cases }] = await Promise.all([
    supabaseAdmin.from("child_payment_entitlements").select("payment_entitlement_id,period_end,learners(id,first_name,parent_lead_id,parent_leads(id,parent_name,email))").eq("status", "paid").gte("period_end", iso(lookback)).lte("period_end", iso(horizon)).order("period_end"),
    supabaseAdmin.from("renewal_cases").select("id,parent_lead_id,source_payment_entitlement_id,status,email_sent_at,proposed_period_start,proposed_period_end,proposed_amount_cents,proposed_service_dates,selected_sessions,draft_subject,draft_body,provisional_delivery_until").in("status", ["ready_to_send", "awaiting_payment", "overdue"]),
  ])
  const casesBySource = new Map((cases || []).map((item) => [`${item.parent_lead_id}:${item.source_payment_entitlement_id}`, item]))
  const groups = new Map<string, RenewalWorkflowRow>()
  for (const item of entitlements || []) {
    const learner = Array.isArray(item.learners) ? item.learners[0] : item.learners
    const parent = learner?.parent_leads && (Array.isArray(learner.parent_leads) ? learner.parent_leads[0] : learner.parent_leads)
    if (!learner || !parent || !learner.parent_lead_id) continue
    const key = `${learner.parent_lead_id}:${item.payment_entitlement_id}`; const existing = groups.get(key); const renewal = casesBySource.get(key)
    if (existing) { existing.learnerNames.push(learner.first_name || "Learner"); continue }
    groups.set(key, { sourcePaymentEntitlementId: item.payment_entitlement_id, parentLeadId: learner.parent_lead_id, parentName: parent.parent_name, email: parent.email, learnerNames: [learner.first_name || "Learner"], periodEnd: item.period_end, caseId: renewal?.id || null, status: renewal?.status || (item.period_end < iso(today) ? "overdue" : "ready_to_send"), emailSentAt: renewal?.email_sent_at || null, proposedPeriodStart: renewal?.proposed_period_start || null, proposedPeriodEnd: renewal?.proposed_period_end || null, proposedAmountCents: renewal?.proposed_amount_cents || null, proposedServiceDates: Array.isArray(renewal?.proposed_service_dates) ? renewal.proposed_service_dates.filter((date): date is string => typeof date === "string") : [], selectedSessions: Array.isArray(renewal?.selected_sessions) ? renewal.selected_sessions.filter((session): session is { date: string; startsAt: string; priceCents: number } => Boolean(session && typeof session === "object" && typeof session.date === "string" && typeof session.startsAt === "string" && typeof session.priceCents === "number")) : [], draftSubject: renewal?.draft_subject || null, draftBody: renewal?.draft_body || null, provisionalDeliveryUntil: renewal?.provisional_delivery_until || null })
  }
  const rows = [...groups.values()].sort((a, b) => a.periodEnd.localeCompare(b.periodEnd))
  return <div className="space-y-8 pb-10"><div className="border-b pb-6"><p className="text-sm font-semibold text-muted-foreground">Protect continuity without mixing it into new-family sales</p><h2 className="mt-1 text-3xl font-bold tracking-tight">Renewals</h2><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Prepare and edit the renewal email, then wait for cleared funds. Overdue renewals stay visible until they are renewed or closed.</p></div><div className="grid divide-y border-y sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div className="px-4 py-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">In renewal queue</p><p className="mt-1 text-2xl font-bold">{rows.length}</p></div><div className="px-4 py-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Awaiting cleared funds</p><p className="mt-1 text-2xl font-bold">{rows.filter((row) => row.status === "awaiting_payment").length}</p></div><div className="px-4 py-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Continuity</p><p className="mt-1 text-sm font-semibold">Pending attendance is explicit and date-bounded</p></div></div><section className="border-t pt-6"><h3 className="text-xl font-bold tracking-tight">Renewal queue</h3><p className="mt-2 text-sm text-muted-foreground">Closed Academy dates are excluded when the email draft is prepared. Every email is editable and requires an explicit send.</p><div className="mt-5">{rows.length ? <RenewalWorkflowTable rows={rows} /> : <p className="border-y py-5 text-sm text-muted-foreground">Nothing needs a renewal conversation in the current queue.</p>}</div></section></div>
}
