"use client"

import { useState } from "react"
import { createTeacherUpdate } from "@/actions/learners"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { SaveActionForm } from "@/components/admin/save-action-form"

export function AiTeacherUpdate({ learnerId, today }: { learnerId: string; today: string }) {
  const [observation, setObservation] = useState(""); const [draft, setDraft] = useState<{ whatHappened: string; whyItMattered: string; nextStep: string; suggestedGoal?: string } | null>(null); const [state, setState] = useState<"idle" | "drafting" | "error">("idle"); const [error, setError] = useState("")
  async function draftUpdate() { setState("drafting"); setError(""); try { const response = await fetch("/api/admin/learner-draft", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ observation }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setDraft(data); setState("idle") } catch (err) { setError(err instanceof Error ? err.message : "Could not create a draft"); setState("error") } }
  return <div className="space-y-5"><div className="border-b pb-4"><p className="font-semibold">Fast internal session note</p><p className="mt-1 text-sm text-muted-foreground">Capture what you noticed in your own words. This is an internal teaching record; family communication is prepared separately each month.</p><Textarea className="mt-3 min-h-28" value={observation} onChange={(event) => setObservation(event.target.value)} placeholder="e.g. Lorenzo started his maths task independently, completed six fraction questions, then needed one prompt to explain his method." /><div className="mt-3 flex flex-wrap items-center gap-3"><Button type="button" disabled={observation.trim().length < 12 || state === "drafting"} onClick={draftUpdate}>{state === "drafting" ? "Drafting…" : "Structure with AI"}</Button><span className="text-xs text-muted-foreground">Optional — a concise factual note can be saved directly below.</span></div>{error ? <p className="mt-2 text-sm text-destructive">{error}</p> : null}</div><SaveActionForm action={createTeacherUpdate} successMessage="Internal session note saved" submitLabel="Save internal session note"><input name="learnerId" type="hidden" value={learnerId} /><div className="max-w-xs space-y-2"><Label>Date</Label><Input name="occurredOn" required type="date" defaultValue={today} /></div><div className="grid gap-4 md:grid-cols-3"><div className="space-y-2"><Label>What happened</Label><Textarea name="whatHappened" required defaultValue={draft?.whatHappened || observation} key={`what-${draft?.whatHappened || observation}`} /></div><div className="space-y-2"><Label>Why it mattered</Label><Textarea name="whyItMattered" required defaultValue={draft?.whyItMattered} key={`why-${draft?.whyItMattered || ""}`} placeholder="Optional AI structure or your own assessment" /></div><div className="space-y-2"><Label>Next small step</Label><Textarea name="nextStep" required defaultValue={draft?.nextStep} key={`next-${draft?.nextStep || ""}`} placeholder="What to try next session" /></div></div>{draft?.suggestedGoal ? <p className="border-l-2 border-primary pl-3 text-sm"><span className="font-semibold">Possible goal:</span> {draft.suggestedGoal}</p> : null}<p className="text-xs text-muted-foreground">Saved notes remain internal. A manager reviews a month of notes before a family summary is drafted.</p></SaveActionForm></div>
}
