"use client";

import { ColumnDef, flexRender, getCoreRowModel, useReactTable } from "@tanstack/react-table";
import { Fragment, useState } from "react";
import { LeadActions } from "@/components/admin/lead-actions";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export type FollowUpLead = { parent_lead_id: string; child_lead_id: string; parent_name: string; email: string; phone: string | null; area: string | null; school_name: string | null; interest_level: string; status: string; source: string; enquiry_type: string; child_age: number; school_year: string | null; curriculum: string | null; support_needs: string[] | null; notes: string | null; focus_group_code: string | null; focus_group_preferred_session: string | null; course_or_exam_board: string | null; preferred_days: string[] | null; preferred_times: string[] | null; preferred_frequency: string | null; created_at: string };
const label = (value: string | null) => value ? value.replaceAll("_", " ") : "—";

export function FamilyFollowUpTable({ leads }: { leads: FollowUpLead[] }) {
  const [expanded, setExpanded] = useState<string | null>(null);
  const columns: ColumnDef<FollowUpLead>[] = [
    { header: "Family", cell: ({ row }) => <div><p className="font-semibold">{row.original.parent_name}</p><p className="text-xs text-muted-foreground">{row.original.email}</p></div> },
    { header: "Child", cell: ({ row }) => <div><p>{row.original.focus_group_code === "igcse_chemistry" ? "IGCSE Chemistry Focus Group" : `Age ${row.original.child_age}`}</p><p className="text-xs text-muted-foreground">{row.original.school_year || "Year to confirm"}{row.original.focus_group_preferred_session ? ` · ${row.original.focus_group_preferred_session === "either" ? "Either session" : row.original.focus_group_preferred_session}` : ""}</p></div> },
    { header: "Availability", cell: ({ row }) => <div><p className="capitalize">{row.original.preferred_days?.join(", ") || "Flexible"}</p><p className="text-xs text-muted-foreground">{row.original.preferred_times?.join(", ") || "Time to confirm"}</p></div> },
    { header: "Follow-up", cell: ({ row }) => <LeadActions leadId={row.original.parent_lead_id} parentName={row.original.parent_name} status={row.original.status as Parameters<typeof LeadActions>[0]["status"]} /> },
    { id: "detail", header: () => <span className="sr-only">Details</span>, cell: ({ row }) => <div className="text-right"><Button onClick={() => setExpanded(expanded === row.original.child_lead_id ? null : row.original.child_lead_id)} size="sm" type="button" variant="ghost">{expanded === row.original.child_lead_id ? "Close" : "Details"}</Button></div> },
  ];
  const table = useReactTable({ data: leads, columns, getCoreRowModel: getCoreRowModel() });
  return <><div className="hidden overflow-hidden rounded-xl border md:block"><Table><TableHeader>{table.getHeaderGroups().map((group) => <TableRow key={group.id}>{group.headers.map((header) => <TableHead key={header.id}>{header.isPlaceholder ? null : flexRender(header.column.columnDef.header, header.getContext())}</TableHead>)}</TableRow>)}</TableHeader><TableBody>{table.getRowModel().rows.map((row) => <Fragment key={row.id}><TableRow className="hover:bg-muted/40">{row.getVisibleCells().map((cell) => <TableCell key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</TableCell>)}</TableRow>{expanded === row.original.child_lead_id ? <TableRow><TableCell className="bg-muted/20 p-5 text-sm" colSpan={columns.length}><div className="grid gap-4 md:grid-cols-3"><div><p className="font-semibold">School and area</p><p className="mt-1 text-muted-foreground">{row.original.school_name || "Not recorded"}{row.original.area ? ` · ${row.original.area}` : ""}</p></div><div><p className="font-semibold">Support and interest</p><p className="mt-1 capitalize text-muted-foreground">{row.original.support_needs?.join(", ") || "Not recorded"} · {label(row.original.interest_level)}</p></div><div><p className="font-semibold">Notes</p><p className="mt-1 text-muted-foreground">{row.original.notes || "No notes"}{row.original.course_or_exam_board ? ` · Course: ${row.original.course_or_exam_board}` : ""}</p></div></div></TableCell></TableRow> : null}</Fragment>)}</TableBody></Table></div><div className="divide-y border-y md:hidden">{leads.map((lead) => <div className="py-4" key={lead.child_lead_id}><button className="flex w-full items-start justify-between gap-3 text-left" onClick={() => setExpanded(expanded === lead.child_lead_id ? null : lead.child_lead_id)} type="button"><span><span className="block font-semibold">{lead.parent_name}</span><span className="block text-sm text-muted-foreground">{lead.focus_group_code === "igcse_chemistry" ? "IGCSE Chemistry Focus Group" : `Age ${lead.child_age}`} · {lead.preferred_days?.join(", ") || "Availability to confirm"}</span></span><span className="text-sm font-semibold text-primary">{expanded === lead.child_lead_id ? "Close" : "Details"}</span></button>{expanded === lead.child_lead_id ? <div className="mt-4 space-y-3 border-t pt-4"><p className="text-sm text-muted-foreground">{lead.email} · {lead.phone || "No phone"}</p><LeadActions leadId={lead.parent_lead_id} parentName={lead.parent_name} status={lead.status as Parameters<typeof LeadActions>[0]["status"]} /></div> : null}</div>)}</div></>;
}
