"use client"

import { useState } from "react"
import { allowPendingRenewalAttendance, closeRenewal, prepareRenewalDraft, sendRenewalEmail, startRenewalCase, updateRenewalSelection } from "@/actions/renewals"
import { recordRenewalPayment } from "@/actions/learners"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

type RenewalSession = { date: string; startsAt: string; priceCents: number }
export type RenewalWorkflowRow = {
  sourcePaymentEntitlementId: string; parentLeadId: string; parentName: string; email: string; learnerNames: string[]; periodEnd: string
  caseId: string | null; status: "ready_to_send" | "awaiting_payment" | "overdue" | "renewed" | "not_renewing"; emailSentAt: string | null
  proposedPeriodStart: string | null; proposedPeriodEnd: string | null; currentPricePlanId: string | null; proposedPricePlanId: string | null; proposedAmountCents: number | null; proposedServiceDates: string[]; selectedSessions: RenewalSession[]
  draftSubject: string | null; draftBody: string | null; provisionalDeliveryUntil: string | null
}

const date = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00Z`))
const iso = (value: Date) => value.toISOString().slice(0, 10)
const price = (cents: number) => new Intl.NumberFormat("en-IE", { style: "currency", currency: "EUR" }).format(cents / 100)
const statusLabel: Record<RenewalWorkflowRow["status"], string> = { ready_to_send: "Prepare email", awaiting_payment: "Awaiting funds", overdue: "Overdue", renewed: "Renewed", not_renewing: "Not renewing" }

type PricePlan = { id: string; name: string; price_cents: number }

export function RenewalWorkflowTable({ rows, pricePlans }: { rows: RenewalWorkflowRow[]; pricePlans: PricePlan[] }) {
  const [expanded, setExpanded] = useState<string | null>(null)
  const toggle = (id: string) => setExpanded(expanded === id ? null : id)
  return <>
    <div className="hidden overflow-hidden rounded-xl border md:block"><table className="w-full text-sm"><thead className="border-b bg-muted/30 text-left text-muted-foreground"><tr><th className="px-4 py-3 font-medium">Family</th><th className="px-4 py-3 font-medium">Learner(s)</th><th className="px-4 py-3 font-medium">Coverage ended</th><th className="px-4 py-3 font-medium">Renewal status</th><th className="px-4 py-3" /></tr></thead><tbody>{rows.map((row) => <><tr className="border-b last:border-0 hover:bg-muted/30" key={row.sourcePaymentEntitlementId}><td className="px-4 py-3"><p className="font-semibold">{row.parentName}</p><p className="text-xs text-muted-foreground">{row.email}</p></td><td className="px-4 py-3">{row.learnerNames.join(", ")}</td><td className="px-4 py-3 font-medium">{date(row.periodEnd)}</td><td className="px-4 py-3"><Badge variant={row.status === "overdue" ? "destructive" : row.status === "renewed" ? "default" : "secondary"}>{statusLabel[row.status]}</Badge></td><td className="px-4 py-3 text-right"><Button onClick={() => toggle(row.sourcePaymentEntitlementId)} size="sm" type="button" variant="ghost">{expanded === row.sourcePaymentEntitlementId ? "Close" : "Open"}</Button></td></tr>{expanded === row.sourcePaymentEntitlementId ? <tr key={`${row.sourcePaymentEntitlementId}-detail`}><td className="bg-muted/20 px-4 py-5" colSpan={5}><RenewalActions pricePlans={pricePlans} row={row} /></td></tr> : null}</>)}</tbody></table></div>
    <div className="divide-y border-y md:hidden">{rows.map((row) => <div className="py-4" key={row.sourcePaymentEntitlementId}><button className="flex w-full items-start justify-between gap-3 text-left" onClick={() => toggle(row.sourcePaymentEntitlementId)} type="button"><span><span className="block font-semibold">{row.parentName}</span><span className="block text-sm text-muted-foreground">{row.learnerNames.join(", ")} · ended {date(row.periodEnd)}</span></span><Badge variant={row.status === "overdue" ? "destructive" : "secondary"}>{statusLabel[row.status]}</Badge></button>{expanded === row.sourcePaymentEntitlementId ? <div className="mt-4 border-t pt-4"><RenewalActions pricePlans={pricePlans} row={row} /></div> : null}</div>)}</div>
  </>
}

function RenewalActions({ row, pricePlans }: { row: RenewalWorkflowRow; pricePlans: PricePlan[] }) {
  const nextStart = new Date(`${row.periodEnd}T12:00:00Z`); nextStart.setUTCDate(nextStart.getUTCDate() + 1)
  const nextEnd = new Date(nextStart); nextEnd.setUTCDate(nextEnd.getUTCDate() + 30)
  if (!row.caseId) return <div><p className="font-semibold">Open this renewal</p><p className="mt-1 text-sm text-muted-foreground">This keeps the family in the queue even after the original paid period ends.</p><form action={startRenewalCase} className="mt-3"><input name="parentLeadId" type="hidden" value={row.parentLeadId}/><input name="sourcePaymentEntitlementId" type="hidden" value={row.sourcePaymentEntitlementId}/><input name="dueOn" type="hidden" value={row.periodEnd}/><Button>Start renewal</Button></form></div>
  return <div className="grid gap-6 xl:grid-cols-3">
    <section><p className="font-semibold">1 · Select the covered sessions</p><p className="mt-1 text-sm text-muted-foreground">Choose the plan and dates for the next paid period. Closure dates are removed automatically.</p><form action={prepareRenewalDraft} className="mt-3 grid gap-2"><input name="caseId" type="hidden" value={row.caseId}/><input name="parentLeadId" type="hidden" value={row.parentLeadId}/><label className="grid gap-1 text-sm font-medium">Plan for next period<select className="h-10 rounded-md border bg-background px-3 font-normal" defaultValue={row.proposedPricePlanId || row.currentPricePlanId || ""} name="pricePlanId" required><option disabled value="">Choose a plan</option>{pricePlans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {price(plan.price_cents)} per session</option>)}</select></label><p className="text-xs text-muted-foreground">The current plan is preselected. A changed plan becomes active only after cleared payment; confirm the suitable group and seat separately.</p><Input defaultValue={row.proposedPeriodStart || iso(nextStart)} name="periodStart" required type="date"/><Input defaultValue={row.proposedPeriodEnd || iso(nextEnd)} name="periodEnd" required type="date"/><Button>Calculate dates and price</Button></form>{row.selectedSessions.length ? <form action={updateRenewalSelection} className="mt-4 space-y-2 border-t pt-4"><input name="caseId" type="hidden" value={row.caseId}/><input name="parentLeadId" type="hidden" value={row.parentLeadId}/><p className="text-sm font-medium">Included sessions · {price(row.proposedAmountCents || 0)}</p>{row.selectedSessions.map((session) => <label className="flex items-center justify-between gap-2 text-sm" key={`${session.date}-${session.startsAt}`}><span className="flex items-center gap-2"><input defaultChecked name="sessionKey" type="checkbox" value={`${session.date}|${session.startsAt}`}/>{date(session.date)} · {session.startsAt}</span><span className="text-muted-foreground">{price(session.priceCents)}</span></label>)}<Button size="sm" variant="outline">Update selected sessions</Button></form> : null}</section>
    <section><p className="font-semibold">2 · Review and send</p>{row.draftSubject && row.draftBody ? <form action={sendRenewalEmail} className="mt-3 grid gap-2"><input name="caseId" type="hidden" value={row.caseId}/><input name="parentLeadId" type="hidden" value={row.parentLeadId}/><Input defaultValue={row.draftSubject} name="subject" required/><textarea className="min-h-48 rounded-md border bg-background p-3 text-sm" defaultValue={row.draftBody} name="body" required/>{row.proposedServiceDates.length ? <p className="text-xs text-muted-foreground">The email lists every included date and time. You can edit the copy before sending.</p> : null}<Button disabled={Boolean(row.emailSentAt)}>{row.emailSentAt ? "Email sent" : "Send renewal email"}</Button></form> : <p className="mt-2 text-sm text-muted-foreground">Calculate the sessions first. You can then remove any date before preparing the email.</p>}</section>
    <section><p className="font-semibold">3 · Continue or close</p><p className="mt-1 text-sm text-muted-foreground">If payment is late, keep attendance running only to an explicit date. Operations labels those seats Payment pending.</p><form action={allowPendingRenewalAttendance} className="mt-3 flex gap-2"><input name="caseId" type="hidden" value={row.caseId}/><input name="parentLeadId" type="hidden" value={row.parentLeadId}/><Input defaultValue={row.provisionalDeliveryUntil || iso(nextStart)} name="throughDate" required type="date"/><Button type="submit" variant="outline">Continue pending</Button></form>{row.provisionalDeliveryUntil ? <p className="mt-2 text-sm font-medium text-amber-700">Pending attendance through {date(row.provisionalDeliveryUntil)}</p> : null}<div className="mt-5 border-t pt-4"><p className="font-semibold">Funds cleared</p><form action={recordRenewalPayment} className="mt-2 grid gap-2"><input name="parentLeadId" type="hidden" value={row.parentLeadId}/><input name="renewalCaseId" type="hidden" value={row.caseId}/><Input defaultValue={iso(new Date())} name="receivedOn" required type="date"/><Input defaultValue={row.proposedAmountCents === null ? "" : (row.proposedAmountCents / 100).toFixed(2)} name="amountEuros" placeholder="Amount (€)" step="0.01" type="number"/><Input defaultValue={row.proposedPeriodStart || iso(nextStart)} name="periodStart" required type="date"/><Input defaultValue={row.proposedPeriodEnd || iso(nextEnd)} name="periodEnd" required type="date"/><Input name="bankReference" placeholder="Bank reference"/><Button>Confirm payment & renew</Button></form></div><form action={closeRenewal} className="mt-4 border-t pt-4"><input name="caseId" type="hidden" value={row.caseId}/><input name="parentLeadId" type="hidden" value={row.parentLeadId}/><Input name="note" placeholder="Optional non-renewal reason"/><Button className="mt-2" type="submit" variant="ghost">Mark not renewing</Button></form></section>
  </div>
}
