"use client"

import { useState } from "react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { closeRenewal, sendRenewalEmail } from "@/actions/renewals"
import { recordRenewalPayment } from "@/actions/learners"

export type RenewalWorkflowRow = { sourcePaymentEntitlementId: string; parentLeadId: string; parentName: string; email: string; learnerNames: string[]; periodEnd: string; caseId: string | null; status: "ready_to_send" | "awaiting_payment" | "overdue" | "renewed" | "not_renewing"; emailSentAt: string | null }
const date = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${value}T12:00:00Z`))
const statusLabel: Record<RenewalWorkflowRow["status"], string> = { ready_to_send: "Email due", awaiting_payment: "Awaiting funds", overdue: "Overdue", renewed: "Renewed", not_renewing: "Not renewing" }

export function RenewalWorkflowTable({ rows }: { rows: RenewalWorkflowRow[] }) {
  const [expanded, setExpanded] = useState<string | null>(null)
  return <><div className="hidden overflow-hidden rounded-xl border md:block"><table className="w-full text-sm"><thead className="border-b bg-muted/30 text-left text-muted-foreground"><tr><th className="px-4 py-3 font-medium">Family</th><th className="px-4 py-3 font-medium">Learner(s)</th><th className="px-4 py-3 font-medium">Coverage ends</th><th className="px-4 py-3 font-medium">Renewal status</th><th className="px-4 py-3" /></tr></thead><tbody>{rows.map((row) => <><tr className="border-b last:border-0 hover:bg-muted/30" key={row.sourcePaymentEntitlementId}><td className="px-4 py-3"><p className="font-semibold">{row.parentName}</p><p className="text-xs text-muted-foreground">{row.email}</p></td><td className="px-4 py-3">{row.learnerNames.join(", ")}</td><td className="px-4 py-3 font-medium">{date(row.periodEnd)}</td><td className="px-4 py-3"><Badge variant={row.status === "overdue" ? "destructive" : row.status === "renewed" ? "default" : "secondary"}>{statusLabel[row.status]}</Badge></td><td className="px-4 py-3 text-right"><Button size="sm" type="button" variant="ghost" onClick={() => setExpanded(expanded === row.sourcePaymentEntitlementId ? null : row.sourcePaymentEntitlementId)}>{expanded === row.sourcePaymentEntitlementId ? "Close" : "Open"}</Button></td></tr>{expanded === row.sourcePaymentEntitlementId ? <tr key={`${row.sourcePaymentEntitlementId}-detail`}><td className="bg-muted/20 px-4 py-5" colSpan={5}><RenewalActions row={row} /></td></tr> : null}</>)}</tbody></table></div><div className="divide-y border-y md:hidden">{rows.map((row) => <div className="py-4" key={row.sourcePaymentEntitlementId}><button className="flex w-full items-start justify-between gap-3 text-left" onClick={() => setExpanded(expanded === row.sourcePaymentEntitlementId ? null : row.sourcePaymentEntitlementId)} type="button"><span><span className="block font-semibold">{row.parentName}</span><span className="block text-sm text-muted-foreground">{row.learnerNames.join(", ")} · ends {date(row.periodEnd)}</span></span><Badge variant={row.status === "overdue" ? "destructive" : "secondary"}>{statusLabel[row.status]}</Badge></button>{expanded === row.sourcePaymentEntitlementId ? <div className="mt-4 border-t pt-4"><RenewalActions row={row} /></div> : null}</div>)}</div></>
}

function RenewalActions({ row }: { row: RenewalWorkflowRow }) {
  const nextStart = new Date(`${row.periodEnd}T12:00:00Z`); nextStart.setUTCDate(nextStart.getUTCDate() + 1); const nextEnd = new Date(nextStart); nextEnd.setUTCDate(nextEnd.getUTCDate() + 30); const iso = (value: Date) => value.toISOString().slice(0, 10)
  if (row.status === "renewed" || row.status === "not_renewing") return <p className="text-sm text-muted-foreground">This renewal is complete. The learner history and prior payment remain unchanged.</p>
  return <div className="grid gap-6 lg:grid-cols-3"><div><p className="font-semibold">1 · Contact family</p><p className="mt-1 text-sm text-muted-foreground">Send the approved renewal email. It records the send time and then waits for cleared funds.</p>{row.emailSentAt ? <p className="mt-3 text-sm font-medium">Sent {new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(row.emailSentAt))}</p> : <form action={sendRenewalEmail} className="mt-3"><input name="parentLeadId" type="hidden" value={row.parentLeadId} /><input name="sourcePaymentEntitlementId" type="hidden" value={row.sourcePaymentEntitlementId} /><input name="dueOn" type="hidden" value={row.periodEnd} /><Button>Send renewal email</Button></form>}</div><div><p className="font-semibold">2 · Funds cleared</p><p className="mt-1 text-sm text-muted-foreground">Confirm the transfer here. The current recurring place carries forward and prepares only the next dated seats.</p>{row.caseId ? <form action={recordRenewalPayment} className="mt-3 grid gap-2 sm:grid-cols-2"><input name="parentLeadId" type="hidden" value={row.parentLeadId} /><input name="renewalCaseId" type="hidden" value={row.caseId} /><Input defaultValue={iso(new Date())} name="receivedOn" required type="date" /><Input name="amountEuros" placeholder="Amount (€)" step="0.01" type="number" /><Input defaultValue={iso(nextStart)} name="periodStart" required type="date" /><Input defaultValue={iso(nextEnd)} name="periodEnd" required type="date" /><Input className="sm:col-span-2" name="bankReference" placeholder="Bank reference" /><Input className="sm:col-span-2" name="note" placeholder="Optional renewal note" /><Button className="sm:col-span-2">Confirm payment & renew</Button></form> : <p className="mt-3 text-sm text-muted-foreground">Send the renewal email first, then this confirmation form becomes available.</p>}</div><div><p className="font-semibold">3 · Family is not continuing</p><p className="mt-1 text-sm text-muted-foreground">Close the renewal without touching their attendance history. It moves to the archived former-families view.</p>{row.caseId ? <form action={closeRenewal} className="mt-3 space-y-2"><input name="caseId" type="hidden" value={row.caseId} /><input name="parentLeadId" type="hidden" value={row.parentLeadId} /><Input name="note" placeholder="Optional reason" /><Button type="submit" variant="outline">Mark not renewing</Button></form> : <p className="mt-3 text-sm text-muted-foreground">Send the email first to open and track this renewal.</p>}</div></div>
}
