import { NextRequest, NextResponse } from "next/server"

import { getResend } from "@/lib/resend"
import { supabaseService } from "@/lib/supabase/service"

type ResendWebhookEvent = {
  type: string
  created_at?: string
  data?: {
    email_id?: string
    bounce?: {
      message?: string
      type?: string
      subType?: string
    }
    error?: {
      message?: string
    }
  }
}

const statusRank: Record<string, number> = {
  pending: 0,
  sent: 1,
  delayed: 2,
  delivered: 3,
  failed: 4,
  bounced: 4,
  suppressed: 4,
}

function detailForEvent(event: ResendWebhookEvent) {
  if (event.type === "email.bounced") {
    return [
      event.data?.bounce?.type,
      event.data?.bounce?.subType,
      event.data?.bounce?.message,
    ]
      .filter(Boolean)
      .join(" · ")
      .slice(0, 500)
  }

  if (event.type === "email.failed") {
    return event.data?.error?.message?.slice(0, 500) || "Delivery failed"
  }

  if (event.type === "email.delivery_delayed") {
    return "Delivery delayed by recipient mail server"
  }

  if (event.type === "email.suppressed") {
    return "Resend suppressed delivery to this recipient"
  }

  return null
}

export async function POST(request: NextRequest) {
  const webhookSecret = process.env.RESEND_WEBHOOK_SECRET
  if (!webhookSecret) {
    return new NextResponse("Webhook not configured", { status: 503 })
  }

  const id = request.headers.get("svix-id")
  const timestamp = request.headers.get("svix-timestamp")
  const signature = request.headers.get("svix-signature")
  if (!id || !timestamp || !signature) {
    return new NextResponse("Missing webhook signature", { status: 400 })
  }

  const payload = await request.text()

  let event: ResendWebhookEvent
  try {
    event = (await getResend().webhooks.verify({
      payload,
      headers: { id, timestamp, signature },
      webhookSecret,
    })) as ResendWebhookEvent
  } catch {
    return new NextResponse("Invalid webhook signature", { status: 400 })
  }

  const nextStatus =
    event.type === "email.sent"
      ? "sent"
      : event.type === "email.delivered"
        ? "delivered"
        : event.type === "email.delivery_delayed"
          ? "delayed"
          : event.type === "email.bounced"
            ? "bounced"
            : event.type === "email.failed"
              ? "failed"
              : event.type === "email.suppressed"
                ? "suppressed"
                : null

  // TAA intentionally does not store open/click engagement events.
  if (!nextStatus) {
    return NextResponse.json({ received: true })
  }

  const resendEmailId = event.data?.email_id
  if (!resendEmailId) {
    return new NextResponse("Missing email id", { status: 400 })
  }

  const supabase = supabaseService()
  const { data: log, error: logError } = await supabase
    .from("email_delivery_log")
    .select("id,status")
    .eq("resend_email_id", resendEmailId)
    .maybeSingle()

  if (logError) {
    console.error("Resend webhook delivery-log lookup failed", {
      code: logError.code,
    })
    return new NextResponse("Temporary webhook error", { status: 500 })
  }

  // Resend may also send events for messages not generated by this app.
  if (!log) {
    return NextResponse.json({ received: true })
  }

  const occurredAt = event.created_at || new Date().toISOString()
  const detail = detailForEvent(event)

  const { error: eventError } = await supabase
    .from("email_delivery_events")
    .insert({
      id,
      email_delivery_log_id: log.id,
      resend_email_id: resendEmailId,
      event_type: event.type,
      occurred_at: occurredAt,
      detail,
    })

  if (eventError?.code === "23505") {
    return NextResponse.json({ received: true })
  }
  if (eventError) {
    console.error("Resend webhook event audit insert failed", {
      code: eventError.code,
    })
    return new NextResponse("Temporary webhook error", { status: 500 })
  }

  const currentRank = statusRank[log.status] ?? 0
  const nextRank = statusRank[nextStatus] ?? 0
  const update: Record<string, string | null> = {
    last_event_at: occurredAt,
  }

  if (nextRank >= currentRank) {
    update.status = nextStatus
    update.delivery_detail = detail
  }

  if (nextStatus === "delivered") update.delivered_at = occurredAt
  if (nextStatus === "bounced") update.bounced_at = occurredAt
  if (nextStatus === "failed") update.failed_at = occurredAt

  const { error: updateError } = await supabase
    .from("email_delivery_log")
    .update(update)
    .eq("id", log.id)

  if (updateError) {
    console.error("Resend webhook delivery status update failed", {
      code: updateError.code,
    })
    return new NextResponse("Temporary webhook error", { status: 500 })
  }

  return NextResponse.json({ received: true })
}
