-- Applied to shared Supabase on 2026-09-23. Source-control mirror.
create table if not exists public.place_offers (
 id uuid primary key default gen_random_uuid(), parent_lead_id uuid not null references public.parent_leads(id) on delete restrict, child_lead_id uuid not null references public.child_leads(id) on delete restrict, weekly_table_template_id uuid not null references public.weekly_table_templates(id) on delete restrict, academy_table_id uuid not null references public.academy_tables(id) on delete restrict, weekday smallint not null check (weekday between 0 and 6), table_number smallint not null check (table_number > 0), seat_number smallint not null check (seat_number > 0), starts_at time not null, duration_minutes integer not null check (duration_minutes between 15 and 360), amount_cents integer not null check (amount_cents >= 0), currency text not null default 'EUR' check (currency = upper(currency) and char_length(currency) = 3), service_period_start date not null, service_period_end date not null, payment_reference text not null unique, access_token_hash text not null unique, status text not null default 'draft' check (status in ('draft','sent','viewed','accepted','expired','cancelled','payment_confirmed')), expires_at timestamptz not null, sent_at timestamptz, accepted_at timestamptz, accepted_ip_hash text, accepted_user_agent text, payment_confirmed_at timestamptz, payment_confirmed_by uuid, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (service_period_end >= service_period_start));
create unique index if not exists place_offers_active_seat on public.place_offers (weekday, academy_table_id, starts_at, seat_number) where status in ('draft','sent','viewed','accepted');
create index if not exists place_offers_parent_lead_idx on public.place_offers (parent_lead_id, created_at desc);
create table if not exists public.parent_portal_access (
 id uuid primary key default gen_random_uuid(), parent_lead_id uuid not null references public.parent_leads(id) on delete restrict, email text not null, auth_user_id uuid references auth.users(id) on delete set null, status text not null default 'invited' check (status in ('invited','active','revoked')), invited_at timestamptz not null default now(), invited_by uuid, activated_at timestamptz, revoked_at timestamptz, revoked_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index if not exists parent_portal_access_family_email_key on public.parent_portal_access (parent_lead_id, lower(email));
create index if not exists parent_portal_access_auth_user_idx on public.parent_portal_access (auth_user_id) where auth_user_id is not null;
create table if not exists public.email_delivery_log (
 id uuid primary key default gen_random_uuid(), parent_lead_id uuid not null references public.parent_leads(id) on delete restrict, place_offer_id uuid references public.place_offers(id) on delete set null, email_kind text not null check (email_kind in ('place_offer','payment_confirmed','portal_access','learning_update')), recipient_email text not null, idempotency_key text not null unique, resend_email_id text, status text not null default 'pending' check (status in ('pending','sent','failed')), error_message text, sent_at timestamptz, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists email_delivery_log_parent_created_idx on public.email_delivery_log (parent_lead_id, created_at desc);
alter table public.place_offers enable row level security;
alter table public.parent_portal_access enable row level security;
alter table public.email_delivery_log enable row level security;
drop policy if exists "parents can view their portal access" on public.parent_portal_access;
create policy "parents can view their portal access" on public.parent_portal_access for select to authenticated using ((select auth.uid()) = auth_user_id and status = 'active');
drop policy if exists "parents can view linked learners" on public.learners;
create policy "parents can view linked learners" on public.learners for select to authenticated using (exists (select 1 from public.parent_portal_access access where access.parent_lead_id = learners.parent_lead_id and access.auth_user_id = (select auth.uid()) and access.status = 'active'));
drop policy if exists "parents can view approved teacher updates" on public.teacher_updates;
create policy "parents can view approved teacher updates" on public.teacher_updates for select to authenticated using (parent_visible = true and exists (select 1 from public.learners learner join public.parent_portal_access access on access.parent_lead_id = learner.parent_lead_id where learner.id = teacher_updates.learner_id and access.auth_user_id = (select auth.uid()) and access.status = 'active'));
