import { BookOpen, Calculator, Clock, Languages, MapPin, Users } from "lucide-react"

import { LeadForm } from "@/components/forms/lead-form"
import { PublicFooter, PublicHeader } from "@/components/shared/public-shell"
import { Card, CardContent } from "@/components/ui/card"

const supportAreas = ["Homework help", "Reading & writing", "Maths confidence", "English support"]
const services = [
  { title: "Homework, done calmly", description: "A focused place to complete school homework, with a tutor nearby to guide, encourage and keep children on track.", icon: BookOpen },
  { title: "Reading & writing", description: "Practical support with reading, writing, comprehension, vocabulary and spelling in English.", icon: Languages },
  { title: "Maths confidence", description: "Time and support to practise core maths, ask questions and build confidence step by step.", icon: Calculator },
  { title: "A reliable routine", description: "A structured hour after school that helps children settle, focus and arrive home with less still to do.", icon: Clock },
  { title: "Small groups", description: "Small, supportive groups so each child is known and can receive appropriate encouragement.", icon: Users },
  { title: "British curriculum aligned", description: "Designed for British and international school families, in an English-speaking learning environment.", icon: MapPin },
]

export default function HomePage() {
  return <main className="min-h-screen"><PublicHeader locale="en" switchHref="/es" />
    <section className="brand-shell flex flex-col gap-16 py-10 md:py-16">
      <section className="brand-hero grid gap-10 p-6 md:p-10 lg:grid-cols-[1fr_380px] lg:items-center">
        <div className="space-y-7"><div className="brand-pill">Now open in Arturo Soria · Ages 4–12</div><div className="space-y-5"><h1 className="max-w-3xl text-4xl font-bold tracking-tight md:text-6xl">British curriculum support for children in Madrid.</h1><p className="max-w-2xl text-lg brand-muted md:text-xl">Calm, small-group after-school support for busy international families — helping children get homework done and build confidence in English, reading, writing and maths.</p><p className="max-w-2xl brand-muted">We are welcoming children aged 4–12 at Calle Asura 40. Apply for a place and we will confirm the best available group and session for your child.</p></div><div className="flex flex-col gap-3 sm:flex-row"><a href="#apply" className="brand-button">Apply for a place</a><a href="#sessions" className="brand-button-secondary">See sessions and pricing</a></div><div className="grid gap-3 sm:grid-cols-2">{supportAreas.map((item) => <Card key={item} className="brand-card"><CardContent className="p-4 text-sm font-medium">{item}</CardContent></Card>)}</div></div>
        <Card className="brand-card border-[color:var(--brand-gold)] bg-[rgba(255,250,240,0.92)]"><CardContent className="space-y-6 p-7"><div><p className="brand-kicker">Simple pricing</p><p className="mt-2 text-5xl font-bold tracking-tight">€25</p><p className="text-lg font-semibold">per child, per session</p></div><div className="space-y-3 border-y py-5 text-sm brand-muted"><p><strong className="text-foreground">Monday, Tuesday, Thursday & Friday</strong></p><p><strong className="text-foreground">17:00–17:50 or 18:00–18:50</strong></p><p>Calle Asura 40, 28043 Madrid<br />First floor, Classroom 3</p></div><p className="text-sm brand-muted">Places are allocated by age group and availability. There is no payment when you apply.</p><a href="#apply" className="brand-button w-full">Apply for a place</a></CardContent></Card>
      </section>
      <section className="grid gap-6 md:grid-cols-[0.8fr_1.2fr]"><Card className="brand-card"><CardContent className="space-y-3 p-6"><p className="brand-kicker">For parents</p><h2 className="text-2xl font-semibold">Less homework stress. More calm at home.</h2></CardContent></Card><Card className="brand-card"><CardContent className="space-y-4 p-6 brand-muted"><p>After a long school day, homework can easily become rushed or stressful. The Afternoon Academy gives children a calm place to settle, focus and complete what they can before they get home.</p><p>It is structured academic support — not childcare, and not a replacement for specialist tutoring. At this stage, our focus is simple: good routines, completed homework and growing confidence.</p></CardContent></Card></section>
      <section id="sessions" className="scroll-mt-10 space-y-6"><div className="max-w-3xl space-y-3"><p className="brand-kicker">What we do</p><h2 className="text-3xl font-bold tracking-tight">A focused hour after school</h2><p className="brand-muted">Every child is different, but every session is designed to be calm, encouraging and purposeful.</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map((service) => { const Icon = service.icon; return <Card key={service.title} className="brand-card"><CardContent className="space-y-4 p-6"><div className="flex h-12 w-12 items-center justify-center rounded-2xl border bg-white/75"><Icon className="h-5 w-5" /></div><div className="space-y-2"><h3 className="font-semibold">{service.title}</h3><p className="text-sm brand-muted">{service.description}</p></div></CardContent></Card> })}</div></section>
      <section className="grid gap-6 lg:grid-cols-2"><Card className="brand-card"><CardContent className="space-y-5 p-6"><p className="brand-kicker">Sessions</p><h2 className="text-3xl font-bold tracking-tight">Choose a time that works</h2><div className="grid gap-3 sm:grid-cols-2">{["17:00–17:50", "18:00–18:50"].map((time) => <div key={time} className="rounded-2xl border bg-white/60 p-4"><p className="text-xl font-semibold">{time}</p><p className="mt-1 text-sm brand-muted">Monday, Tuesday, Thursday & Friday</p></div>)}</div></CardContent></Card><Card className="brand-card"><CardContent className="space-y-5 p-6"><p className="brand-kicker">Location</p><h2 className="text-3xl font-bold tracking-tight">Calle Asura 40</h2><p className="brand-muted">First floor, Classroom 3 · 28043 Madrid · Arturo Soria</p><p className="brand-muted">A bright, dedicated classroom with space for small groups to work calmly after school.</p><a href="/location" className="brand-button-secondary">See the location</a></CardContent></Card></section>
      <section id="apply" className="scroll-mt-10"><Card className="brand-form-panel"><CardContent className="grid gap-8 p-6 md:p-8 lg:grid-cols-[360px_1fr]"><div className="space-y-4"><div className="brand-pill-warm">Apply now</div><div className="space-y-3"><h2 className="text-3xl font-bold tracking-tight">Apply for a place</h2><p className="brand-muted">Tell us a little about your child and which sessions could work for your family.</p><p className="text-sm brand-muted">We will be in touch to confirm availability and next steps. Applying does not commit you to a booking or payment.</p></div></div><LeadForm language="en" /></CardContent></Card></section>
    </section><PublicFooter locale="en" switchHref="/es" /></main>
}
